<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-20T15:33:58 ICT" name="Default suite" finished-at="2025-05-20T15:34:24 ICT" duration-ms="25915">
    <groups>
    </groups>
    <test started-at="2025-05-20T15:33:58 ICT" name="Default test" finished-at="2025-05-20T15:34:24 ICT" duration-ms="25915">
      <class name="TCRise.autodashboard">
        <test-method is-config="true" signature="setup()[pri:0, instance:TCRise.autodashboard@76b07f29]" started-at="2025-05-20T15:33:58 ICT" name="setup" finished-at="2025-05-20T15:34:07 ICT" duration-ms="9059" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testInvoiceStats()[pri:0, instance:TCRise.autodashboard@76b07f29]" started-at="2025-05-20T15:34:07 ICT" name="testInvoiceStats" finished-at="2025-05-20T15:34:23 ICT" duration-ms="16579" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Bảng Not Paid không có dữ liệu expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Bảng Not Paid không có dữ liệu expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at TCRise.autodashboard.testInvoiceStats(autodashboard.java:48)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvoiceStats -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:TCRise.autodashboard@76b07f29]" started-at="2025-05-20T15:34:23 ICT" name="teardown" finished-at="2025-05-20T15:34:24 ICT" duration-ms="243" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- TCRise.autodashboard -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
